package com.sdr.guide.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.sdr.guide.service.persistence.BookFilePK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BookFile service. Represents a row in the &quot;test_BookFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.sdr.guide.model.impl.BookFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.sdr.guide.model.impl.BookFileImpl}.
 * </p>
 *
 * @author leegyuseong
 * @see BookFile
 * @see com.sdr.guide.model.impl.BookFileImpl
 * @see com.sdr.guide.model.impl.BookFileModelImpl
 * @generated
 */
public interface BookFileModel extends BaseModel<BookFile>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a book file model instance should use the {@link BookFile} interface instead.
     */

    /**
     * Returns the primary key of this book file.
     *
     * @return the primary key of this book file
     */
    public BookFilePK getPrimaryKey();

    /**
     * Sets the primary key of this book file.
     *
     * @param primaryKey the primary key of this book file
     */
    public void setPrimaryKey(BookFilePK primaryKey);

    /**
     * Returns the gusetbook ID of this book file.
     *
     * @return the gusetbook ID of this book file
     */
    public int getGusetbookId();

    /**
     * Sets the gusetbook ID of this book file.
     *
     * @param gusetbookId the gusetbook ID of this book file
     */
    public void setGusetbookId(int gusetbookId);

    /**
     * Returns the file ID of this book file.
     *
     * @return the file ID of this book file
     */
    public int getFileId();

    /**
     * Sets the file ID of this book file.
     *
     * @param fileId the file ID of this book file
     */
    public void setFileId(int fileId);

    /**
     * Returns the file name of this book file.
     *
     * @return the file name of this book file
     */
    @AutoEscape
    public String getFileName();

    /**
     * Sets the file name of this book file.
     *
     * @param fileName the file name of this book file
     */
    public void setFileName(String fileName);

    /**
     * Returns the file type of this book file.
     *
     * @return the file type of this book file
     */
    @AutoEscape
    public String getFileType();

    /**
     * Sets the file type of this book file.
     *
     * @param fileType the file type of this book file
     */
    public void setFileType(String fileType);

    /**
     * Returns the file location of this book file.
     *
     * @return the file location of this book file
     */
    @AutoEscape
    public String getFileLocation();

    /**
     * Sets the file location of this book file.
     *
     * @param fileLocation the file location of this book file
     */
    public void setFileLocation(String fileLocation);

    /**
     * Returns the group ID of this book file.
     *
     * @return the group ID of this book file
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this book file.
     *
     * @param groupId the group ID of this book file
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this book file.
     *
     * @return the company ID of this book file
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this book file.
     *
     * @param companyId the company ID of this book file
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this book file.
     *
     * @return the user ID of this book file
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this book file.
     *
     * @param userId the user ID of this book file
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this book file.
     *
     * @return the user uuid of this book file
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this book file.
     *
     * @param userUuid the user uuid of this book file
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this book file.
     *
     * @return the user name of this book file
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this book file.
     *
     * @param userName the user name of this book file
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this book file.
     *
     * @return the create date of this book file
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this book file.
     *
     * @param createDate the create date of this book file
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this book file.
     *
     * @return the modified date of this book file
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this book file.
     *
     * @param modifiedDate the modified date of this book file
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the delete date of this book file.
     *
     * @return the delete date of this book file
     */
    public Date getDeleteDate();

    /**
     * Sets the delete date of this book file.
     *
     * @param deleteDate the delete date of this book file
     */
    public void setDeleteDate(Date deleteDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.sdr.guide.model.BookFile bookFile);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.sdr.guide.model.BookFile> toCacheModel();

    @Override
    public com.sdr.guide.model.BookFile toEscapedModel();

    @Override
    public com.sdr.guide.model.BookFile toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
