package com.sdr.guide.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.sdr.guide.model.BookFile;
import com.sdr.guide.service.BookFileLocalServiceUtil;

/**
 * The extended model base implementation for the BookFile service. Represents a row in the &quot;test_BookFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BookFileImpl}.
 * </p>
 *
 * @author leegyuseong
 * @see BookFileImpl
 * @see com.sdr.guide.model.BookFile
 * @generated
 */
public abstract class BookFileBaseImpl extends BookFileModelImpl
    implements BookFile {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a book file model instance should use the {@link BookFile} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BookFileLocalServiceUtil.addBookFile(this);
        } else {
            BookFileLocalServiceUtil.updateBookFile(this);
        }
    }
}
